services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: migracao
      MYSQL_USER: vinicius
      MYSQL_PASSWORD: vinicius
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  postgres_db:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: carga
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: vinicius
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin_dashboard:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: vinicius@vinicius.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network
    depends_on:
      - postgres_db
      - mysql_db
    restart: unless-stopped

  phpmyadmin_dashboard:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root_password
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app_network
    depends_on:
      - mysql_db
    restart: unless-stopped

volumes:
  mysql_data:
  postgres_data:
  pgadmin_data:

networks:
  app_network:
    driver: bridge